apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: openshift-5-container
  title: openshift-5-container
  description: "This hands-on lab puts attendees in the role of a platform team
    responsible for onboarding and operating applications on a shared OpenShift
    environment. They will use GitOps to onboard an application, apply access,
    network and resource controls, and manage workloads competing for shared
    platform resources.  A production issue will then be introduced and
    attendees will use metrics, logs, events, traces and OpenShift 5 AI-assisted
    capabilities to investigate the problem. They will need to validate the AI
    recommendations, identify the root cause and implement the final fix through
    GitOps.  The lab will also cover improvements carried forward from OpenShift
    4 around platform management, observability, multitenancy, workload
    management and application lifecycle. "
  annotations:
    ph.rhdp.io/content-type: lab
    ph.rhdp.io/deployment-mode: rhdp_published
    ph.rhdp.io/github-user: waynedovey
    ph.rhdp.io/owner: jboeselm@redhat.com
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhpds/openshift-5-container
    ph.rhdp.io/created-at: 2026-08-24T13:48:28.033Z
  tags:
    - publishing-house
    - lab
    - rhdp-published
  links:
    - url: https://github.com/rhpds/openshift-5-container
      title: Repository
      icon: github
    - url: https://devspaces.apps.ocpv-infra02.wdc07.infra.demo.redhat.com#https://github.com/rhpds/openshift-5-container
      title: Open in DevSpaces
      icon: catalog
    - url: https://central-api-publishing-house.apps.ocpv-infra02.wdc07.infra.demo.redhat.com
      title: Central
      icon: dashboard
spec:
  type: content
  lifecycle: experimental
  owner: rhdp-team
  system: publishing-house
